[0;1;31m√ó[0m gestione_doc.service - Gunicorn instance to serve gestione_doc
     Loaded: loaded (]8;;file://documenti/etc/systemd/system/gestione_doc.service/etc/systemd/system/gestione_doc.service]8;;; [0;1;32menabled[0m; preset: [0;1;32menabled[0m)
     Active: [0;1;31mfailed[0m (Result: exit-code) since Thu 2025-05-15 09:42:22 UTC; 1min 41s ago
   Duration: 3.209s
 Invocation: 654e77ac97f44d0abb51034f0edb4e43
    Process: 17493 ExecStart=/var/www/gestione_doc/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 app:app [0;1;31m(code=exited, status=3)[0m
   Main PID: 17493 (code=exited, status=3)
   Mem peak: 128M
        CPU: 2.980s

May 15 09:42:21 documenti gunicorn[17496]: sqlalchemy.exc.InvalidRequestError: Table 'admin_log' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
May 15 09:42:21 documenti gunicorn[17496]: [2025-05-15 09:42:21 +0000] [17496] [INFO] Worker exiting (pid: 17496)
May 15 09:42:22 documenti gunicorn[17493]: [2025-05-15 09:42:22 +0000] [17493] [ERROR] Worker (pid:17494) exited with code 3
May 15 09:42:22 documenti gunicorn[17493]: [2025-05-15 09:42:22 +0000] [17493] [ERROR] Worker (pid:17496) was sent SIGTERM!
May 15 09:42:22 documenti gunicorn[17493]: [2025-05-15 09:42:22 +0000] [17493] [ERROR] Worker (pid:17495) was sent SIGTERM!
May 15 09:42:22 documenti gunicorn[17493]: [2025-05-15 09:42:22 +0000] [17493] [ERROR] Shutting down: Master
May 15 09:42:22 documenti gunicorn[17493]: [2025-05-15 09:42:22 +0000] [17493] [ERROR] Reason: Worker failed to boot.
May 15 09:42:22 documenti systemd[1]: [0;1;39m[0;1;31m[0;1;39mgestione_doc.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED[0m
May 15 09:42:22 documenti systemd[1]: [0;1;38:5:185m[0;1;39m[0;1;38:5:185mgestione_doc.service: Failed with result 'exit-code'.[0m
May 15 09:42:22 documenti systemd[1]: gestione_doc.service: Consumed 2.980s CPU time, 128M memory peak.
